name: 2023-MIC-DL-recon

channels:
  - conda-forge

dependencies:
  - parallelproj >=1.5
  - matplotlib
  - scipy
  - nibabel
  - ipython
  - jupyter
  - jupyter_nbextensions_configurator
  - jupytext
  - ipydrawio
  - ipydrawio-export
  - pytorch >= 2.0
  - torchmetrics
  - cupy
