name: 2023-MIC-DL-recon

channels:
  - conda-forge

dependencies:
  - parallelproj >=1.4
  - matplotlib
  - scipy
  - ipython
  - jupyter
  - jupyter_nbextensions_configurator
  - jupytext
  - pytorch >= 2.0
  - torchmetrics
  - cupy
